name: Release
on:
  push:
    tags: [v*]
jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Setup Perl
      uses: shogo82148/actions-setup-perl@v1
    - name: Install Module::Build
      run: cpanm Module::Build
    - name: Package the Release
      id: package
      run: perl Build.PL && ./Build manifest && ./Build dist && echo "tarball=$(./Build tarball_name )" >> $GITHUB_OUTPUT
    - name: Generate Release Changes
      run: ./Build latest_changes
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: Release ${{ github.ref_name }}
        body_path: latest_changes.md
        files: ${{ steps.package.outputs.tarball }}
